### ISSUE TITLE
Not a valid version of Chef - 11.18.6

### ISSUE THREAD

**Issue by ghost** [chef/vagrant-omnibus#112]
```
There are errors in the configuration of this machine. Please fix the following errors and try again:

vagrant-omnibus:
* '11.18.6' is not a valid version of Chef.

A list of valid versions can be found at: http://www.opscode.com/chef/install/
```

Attempting to set this version in the Vagrant file: `config.omnibus.chef_version = '11.18.6'`

This version has a fix for issue: https://github.com/chef/chef/issues/2786. Release of Chef 11.18.6: https://www.chef.io/blog/2015/01/29/chef-11-18-6-released.

The client can be downloaded via: https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-windows-11.18.6-1.windows.msi

**Comment by tas50** [comment]
I'm closing this out at this point since we no longer support Chef 11.
