### ISSUE TITLE
Issue with Chef client 12.11.18

### ISSUE THREAD

**Issue by stormerider** [chef/vagrant-omnibus#128]
https://gist.github.com/stormerider/6866b3f70855d7874700c70a7e385031

If I install the latest stable chef-client release via vagrant-omnibus, the chef run errors out with chef-zero issues (notably `#<ChefZero::RestErrorResponse: 404: Object not found: chefzero://localhost:8889/nodes/vagrant-158e34aa>`). I've provided a generic Vagrantfile, Berksfile, and the log of `vagrant up` for others to test and reproduce.

**Comment by mikeg250** [comment]
I'm seeing nearly identical error (with vagrant script that ran fine previous to 12.11.18):
   `/usr/bin/chef-solo:52:in <main>`
   `INFO: HTTP Request Returned 404 Not Found: Object not found:    chefzero://localhost:8889/nodes/vagrant-edc876f4`
   `INFO: POST /organizations/chef/nodes`
   `INFO: #<ChefZero::RestErrorResponse: 404: Parent not found: chefzero://localhost:8889/nodes>`

Tested on both DigitalOcean & Linode with Ubuntu 14.04

**Comment by mistermoe** [comment]
you can track the bug y'all are experiencing [here](https://github.com/chef/chef/issues/4948)

**Comment by tas50** [comment]
I'm going to close this out at this point since we no longer support Chef 12.
