### ISSUE TITLE
Vagrant 1.8.4 crashes when vagrant-omnibus is used with winrm

### ISSUE THREAD

**Issue by olivierlemasle** [chef/vagrant-omnibus#130]
The bug has already been reported in vagrant repo: https://github.com/mitchellh/vagrant/issues/7459

Here is the stacktrace: https://gist.github.com/olivierlemasle/a173b1077e784c224b3c345317479ee7

Similar issue has already been fixed in vagrant-hostmanager: https://github.com/devopsgroup-io/vagrant-hostmanager/issues/198

**Comment by jqassar** [comment]
Updated PR: https://github.com/olivierlemasle/vagrant-omnibus/pull/1

**Comment by tas50** [comment]
Fixed by #135
